(() => {
'use strict';
const $=id=>document.getElementById(id);
const fmt=n=>Number.isFinite(n)?(Math.abs(n)<1e-12?0:Number(n.toFixed(10))).toString():String(n);
const escapeHtml=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let angleDeg=true, seqType='arith';

// Navigation / theme
const savedTheme=localStorage.getItem('mathbox-theme'); if(savedTheme==='dark') document.body.classList.add('dark');
$('themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('mathbox-theme',document.body.classList.contains('dark')?'dark':'light');$('themeToggle').textContent=document.body.classList.contains('dark')?'☀️':'🌙';drawGraph()};
$('themeToggle').textContent=document.body.classList.contains('dark')?'☀️':'🌙';
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.page).classList.add('active');if(b.dataset.page==='graph')setTimeout(drawGraph,30)});

// History
const HISTORY_KEY='mathbox-history-v4';
function addHistory(type,input,result){let h=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');h.unshift({type,input,result,time:new Date().toLocaleString('zh-TW')});h=h.slice(0,80);localStorage.setItem(HISTORY_KEY,JSON.stringify(h));renderHistory()}
function renderHistory(){const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');$('historyList').innerHTML=h.length?h.map((x,i)=>`<div class="history-item"><div><div class="history-value">${escapeHtml(x.type)}：${escapeHtml(x.input)}</div><div>${escapeHtml(x.result)}</div><div class="history-meta">${escapeHtml(x.time)}</div></div><button class="secondary" data-del-history="${i}">刪除</button></div>`).join(''):'<div class="empty">目前沒有計算紀錄</div>';document.querySelectorAll('[data-del-history]').forEach(b=>b.onclick=()=>{let a=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');a.splice(+b.dataset.delHistory,1);localStorage.setItem(HISTORY_KEY,JSON.stringify(a));renderHistory()})}
$('clearHistory').onclick=()=>{if(confirm('確定要清除全部紀錄嗎？')){localStorage.removeItem(HISTORY_KEY);renderHistory()}};renderHistory();

// Expression engine
function factorial(n){n=Number(n);if(!Number.isInteger(n)||n<0||n>170)throw Error('階乘只支援 0～170 的整數');let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function prepareExpr(expr){let s=String(expr).trim().replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('π','PI').replaceAll('√','sqrt').replace(/\b(log10|lg)\b/g,'log10').replace(/\^/g,'**');if(!/^[0-9A-Za-z_+\-*/().,%\s]+$/.test(s))throw Error('含有不支援的符號');s=s.replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');s=s.replace(/\b(ln|log10|log|sin|cos|tan|sqrt|abs|exp|floor|ceil|round)\s*\(/g,'$1(');s=s.replace(/(\d|\)|PI|E|x)\s*(?=(PI|E|x|sin|cos|tan|sqrt|abs|ln|log10|log)\s*\()/g,'$1*');s=s.replace(/(\d|\)|PI|E|x)\s*(?=(PI|E|x))/g,'$1*');return s}
function evaluateExpression(expr,x=0){let s=prepareExpr(expr);if((s.match(/\(/g)||[]).length!==(s.match(/\)/g)||[]).length)throw Error('括號數量不一致');if(/!/.test(s)){s=s.replace(/(\d+(?:\.\d+)?|\([^()]+\))!/g,'factorial($1)')};const args=['sin','cos','tan','sqrt','abs','ln','log','log10','exp','floor','ceil','round','factorial','PI','E','x'];const vals=[a=>angleDeg?Math.sin(a*Math.PI/180):Math.sin(a),a=>angleDeg?Math.cos(a*Math.PI/180):Math.cos(a),a=>angleDeg?Math.tan(a*Math.PI/180):Math.tan(a),Math.sqrt,Math.abs,Math.log,Math.log10||((a)=>Math.log(a)/Math.LN10),Math.log10||((a)=>Math.log(a)/Math.LN10),Math.exp,Math.floor,Math.ceil,Math.round,factorial,Math.PI,Math.E,x];const fn=new Function(...args,'return ('+s+');');const v=fn(...vals);if(!Number.isFinite(v))throw Error('結果不是有限數值');return v}
$('angleMode').onclick=()=>{angleDeg=!angleDeg;$('angleMode').textContent=angleDeg?'度 DEG':'弧度 RAD';$('angleMode').classList.toggle('active',angleDeg)};
function calcNow(){const input=$('calcDisplay').value;if(!input.trim())return;try{const v=evaluateExpression(input);$('calcDisplay').value=fmt(v);addHistory('計算機',input,fmt(v))}catch(e){$('calcDisplay').value='錯誤：'+e.message}}
document.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>{const v=b.dataset.calc,d=$('calcDisplay');if(v==='=')return calcNow();if(v==='C')d.value='';else if(v==='⌫')d.value=d.value.slice(0,-1);else{d.value+=v;d.focus()}});$('calcDisplay').addEventListener('keydown',e=>{if(e.key==='Enter')calcNow()});

// Quadratic
$('solveQuadratic').onclick=()=>{const a=+$('qa').value,b=+$('qb').value,c=+$('qc').value,r=$('quadraticResult');if(!Number.isFinite(a+b+c)||a===0){r.innerHTML='<span class="error">a 不可為 0，且三個係數都必須是數字。</span>';return}const D=b*b-4*a*c;let html=`<div class="result-title">判別式 Δ = ${fmt(D)}</div><div class="step">Δ = b² − 4ac = ${fmt(b)}² − 4(${fmt(a)})(${fmt(c)}) = ${fmt(D)}</div>`;if(D>0){const x1=(-b+Math.sqrt(D))/(2*a),x2=(-b-Math.sqrt(D))/(2*a);html+=`<div class="step">x = (−b ± √Δ)/(2a)</div><div class="success">x₁ = ${fmt(x1)}，x₂ = ${fmt(x2)}</div>`}else if(D===0){const x=-b/(2*a);html+=`<div class="success">重根：x = ${fmt(x)}</div>`}else{const re=-b/(2*a),im=Math.sqrt(-D)/(2*a);html+=`<div>無實數根。</div><div class="success">複數根：x₁ = ${fmt(re)} + ${fmt(im)}i，x₂ = ${fmt(re)} − ${fmt(im)}i</div>`}r.innerHTML=html;addHistory('二次方程式',`a=${a}, b=${b}, c=${c}`,D>=0?html.replace(/<[^>]+>/g,' '):'無實數根')};

// Graph
const canvas=$('graphCanvas'),ctx=canvas.getContext('2d');let view={xmin:-10,xmax:10,ymin:-10,ymax:10},drag=false,last={x:0,y:0};
function syncView(){view.xmin=+$('xMin').value;view.xmax=+$('xMax').value;view.ymin=+$('yMin').value;view.ymax=+$('yMax').value}
function drawGraph(){try{syncView();if(!(view.xmax>view.xmin&&view.ymax>view.ymin))throw Error('座標範圍無效');const w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);const dark=document.body.classList.contains('dark'),grid=dark?'#334056':'#dfe6ef',text=dark?'#aeb9cc':'#64748b',axis=dark?'#edf2ff':'#334155';const X=x=>(x-view.xmin)/(view.xmax-view.xmin)*w,Y=y=>h-(y-view.ymin)/(view.ymax-view.ymin)*h;ctx.strokeStyle=grid;ctx.lineWidth=1;const stepX=niceStep((view.xmax-view.xmin)/10),stepY=niceStep((view.ymax-view.ymin)/10);for(let x=Math.ceil(view.xmin/stepX)*stepX;x<=view.xmax;x+=stepX){ctx.beginPath();ctx.moveTo(X(x),0);ctx.lineTo(X(x),h);ctx.stroke()}for(let y=Math.ceil(view.ymin/stepY)*stepY;y<=view.ymax;y+=stepY){ctx.beginPath();ctx.moveTo(0,Y(y));ctx.lineTo(w,Y(y));ctx.stroke()}ctx.strokeStyle=axis;ctx.lineWidth=1.5;if(view.xmin<=0&&view.xmax>=0){ctx.beginPath();ctx.moveTo(X(0),0);ctx.lineTo(X(0),h);ctx.stroke()}if(view.ymin<=0&&view.ymax>=0){ctx.beginPath();ctx.moveTo(0,Y(0));ctx.lineTo(w,Y(0));ctx.stroke()}ctx.fillStyle=text;ctx.font='12px sans-serif';for(let x=Math.ceil(view.xmin/stepX)*stepX;x<=view.xmax;x+=stepX)if(Math.abs(x)>1e-9)ctx.fillText(fmt(x),X(x)+3,Math.min(h-4,Math.max(14,Y(0)+14)));for(let y=Math.ceil(view.ymin/stepY)*stepY;y<=view.ymax;y+=stepY)if(Math.abs(y)>1e-9)ctx.fillText(fmt(y),Math.max(3,X(0)+5),Y(y)-4);const expr=$('functionInput').value;if(!expr)return;ctx.strokeStyle='#4169e1';ctx.lineWidth=2.5;ctx.beginPath();let started=false,prevY=null;for(let px=0;px<w;px++){const x=view.xmin+(view.xmax-view.xmin)*px/(w-1);let y;try{y=evaluateExpression(expr,x)}catch{continue}if(!Number.isFinite(y)||Math.abs(y)>1e7){started=false;prevY=null;continue}const py=Y(y);if(!started||prevY===null||Math.abs(py-prevY)>h*1.5){ctx.moveTo(px,py);started=true}else ctx.lineTo(px,py);prevY=py}ctx.stroke();$('graphMessage').textContent=''}catch(e){$('graphMessage').textContent=e.message}}
function niceStep(v){const p=10**Math.floor(Math.log10(v||1)),q=v/p;return (q<=1?1:q<=2?2:q<=5?5:10)*p}
$('drawGraph').onclick=drawGraph;$('resetGraph').onclick=()=>{$('functionInput').value='x^2-4';$('xMin').value=-10;$('xMax').value=10;$('yMin').value=-10;$('yMax').value=10;drawGraph()};$('functionInput').addEventListener('keydown',e=>{if(e.key==='Enter')drawGraph()});document.querySelectorAll('[data-insert]').forEach(b=>b.onclick=()=>{$('functionInput').value+=b.dataset.insert;$('functionInput').focus()});canvas.addEventListener('pointerdown',e=>{drag=true;last={x:e.clientX,y:e.clientY};canvas.classList.add('dragging');canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;const sx=(view.xmax-view.xmin)/canvas.clientWidth,sy=(view.ymax-view.ymin)/canvas.clientHeight;view.xmin-=dx*sx;view.xmax-=dx*sx;view.ymin+=dy*sy;view.ymax+=dy*sy;$('xMin').value=view.xmin;$('xMax').value=view.xmax;$('yMin').value=view.ymin;$('yMax').value=view.ymax;last={x:e.clientX,y:e.clientY};drawGraph()});canvas.addEventListener('pointerup',()=>{drag=false;canvas.classList.remove('dragging')});canvas.addEventListener('dblclick',()=>{$('resetGraph').click()});canvas.addEventListener('wheel',e=>{e.preventDefault();syncView();const factor=e.deltaY<0?.82:1.22;const r=canvas.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width,my=(e.clientY-r.top)/r.height,cx=view.xmin+mx*(view.xmax-view.xmin),cy=view.ymax-my*(view.ymax-view.ymin);view.xmin=cx+(view.xmin-cx)*factor;view.xmax=cx+(view.xmax-cx)*factor;view.ymin=cy+(view.ymin-cy)*factor;view.ymax=cy+(view.ymax-cy)*factor;$('xMin').value=view.xmin;$('xMax').value=view.xmax;$('yMin').value=view.ymin;$('yMax').value=view.ymax;drawGraph()},{passive:false});

// Function analysis
$('analyzeFunction').onclick=()=>{const expr=$('analysisInput').value,a=+$('analysisMin').value,b=+$('analysisMax').value,r=$('analysisResult');if(!(b>a)){r.innerHTML='<span class="error">分析範圍無效。</span>';return}try{const y0=evaluateExpression(expr,0);let roots=[],min={x:a,y:Infinity},max={x:a,y:-Infinity};const N=1600,dx=(b-a)/N;let px=a,py=evaluateExpression(expr,px);for(let i=0;i<=N;i++){const x=a+i*dx;let y;try{y=evaluateExpression(expr,x)}catch{continue}if(Number.isFinite(y)){if(y<min.y)min={x,y};if(y>max.y)max={x,y};if(i>0&&Number.isFinite(py)&&y*py<0){let lo=px,hi=x;for(let k=0;k<35;k++){const mid=(lo+hi)/2;const ym=evaluateExpression(expr,mid);if(evaluateExpression(expr,lo)*ym<=0)hi=mid;else lo=mid}roots.push((lo+hi)/2)}if(Math.abs(y)<1e-8)roots.push(x);px=x;py=y}}roots=[...new Set(roots.map(x=>x.toFixed(7)))].map(Number);let html=`<div class="result-title">分析結果</div><div>y 截距：(${fmt(0)}, ${fmt(y0)})</div><div>x 截距：${roots.length?roots.map(x=>fmt(x)).join('、'):'範圍內沒有找到'}</div><div>近似最小值：(${fmt(min.x)}, ${fmt(min.y)})</div><div>近似最大值：(${fmt(max.x)}, ${fmt(max.y)})</div>`;const m=expr.replace(/\s+/g,'').match(/^([+-]?\d*\.?\d*)\*?x\^2([+-]\d*\.?\d*)\*?x([+-]\d*\.?\d*)$/i);if(m){const A=m[1]===''||m[1]==='+'?1:m[1]==='-'?-1:parseFloat(m[1]),B=parseFloat(m[2]),C=parseFloat(m[3]),vx=-B/(2*A),vy=A*vx*vx+B*vx+C;html+=`<div class="step">二次函數頂點：(${fmt(vx)}, ${fmt(vy)})；對稱軸：x = ${fmt(vx)}</div>`}r.innerHTML=html;addHistory('函數分析',expr,html.replace(/<[^>]+>/g,' '))}catch(e){r.innerHTML='<span class="error">'+escapeHtml(e.message)+'</span>'}};

// Statistics
function parseNumbers(s){const a=s.trim().split(/[\s,，;；]+/).filter(Boolean).map(Number);if(!a.length||a.some(x=>!Number.isFinite(x)))throw Error('請輸入有效數字');return a}
$('calcStats').onclick=()=>{try{const a=parseNumbers($('statsInput').value),s=[...a].sort((x,y)=>x-y),n=a.length,mean=a.reduce((x,y)=>x+y,0)/n,median=n%2?s[(n-1)/2]:(s[n/2-1]+s[n/2])/2,pops=a.reduce((z,x)=>z+(x-mean)**2,0)/n,sample=n>1?a.reduce((z,x)=>z+(x-mean)**2,0)/(n-1):NaN,q=p=>{const pos=(s.length-1)*p,lo=Math.floor(pos),hi=Math.ceil(pos);return lo===hi?s[lo]:s[lo]+(s[hi]-s[lo])*(pos-lo)},freq={};s.forEach(x=>freq[x]=(freq[x]||0)+1);const maxf=Math.max(...Object.values(freq)),modes=maxf>1?Object.keys(freq).filter(k=>freq[k]===maxf).map(Number):[];const html=`<div class="result-title">統計結果（n=${n}）</div><div>平均數：${fmt(mean)}</div><div>中位數：${fmt(median)}</div><div>眾數：${modes.length?modes.map(fmt).join('、'):'無重複眾數'}</div><div>母體變異數：${fmt(pops)}</div><div>母體標準差：${fmt(Math.sqrt(pops))}</div><div>樣本變異數：${fmt(sample)}</div><div>樣本標準差：${fmt(Math.sqrt(sample))}</div><div>Q1：${fmt(q(.25))}　Q3：${fmt(q(.75))}　IQR：${fmt(q(.75)-q(.25))}</div><div>最小：${fmt(s[0])}　最大：${fmt(s[n-1])}　全距：${fmt(s[n-1]-s[0])}</div>`;$('statsResult').innerHTML=html;addHistory('統計',$('statsInput').value,html.replace(/<[^>]+>/g,' '))}catch(e){$('statsResult').innerHTML='<span class="error">'+e.message+'</span>'}};

// Matrix
function parseMatrix(s){const rows=s.trim().split(/[;\n]+/).map(r=>r.trim()).filter(Boolean).map(r=>r.split(/[ ,，]+/).filter(Boolean).map(Number));if(!rows.length||rows.some(r=>!r.length||r.some(x=>!Number.isFinite(x))))throw Error('矩陣格式錯誤');const cols=rows[0].length;if(rows.some(r=>r.length!==cols))throw Error('每一列必須有相同欄數');return rows}
function matrixText(A){return A.map(r=>r.map(fmt).join('　')).join('<br>')}
function addMat(A,B){if(A.length!==B.length||A[0].length!==B[0].length)throw Error('矩陣維度不同');return A.map((r,i)=>r.map((x,j)=>x+B[i][j]))}
function mulMat(A,B){if(A[0].length!==B.length)throw Error('A 的欄數必須等於 B 的列數');return A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0)))}
function det(A){if(A.length!==A[0].length)throw Error('det 只適用方陣');const n=A.length,M=A.map(r=>r.slice());let d=1;for(let i=0;i<n;i++){let p=i;for(let k=i+1;k<n;k++)if(Math.abs(M[k][i])>Math.abs(M[p][i]))p=k;if(Math.abs(M[p][i])<1e-12)return 0;if(p!==i){[M[p],M[i]]=[M[i],M[p]];d*=-1}const v=M[i][i];d*=v;for(let k=i+1;k<n;k++){const f=M[k][i]/v;for(let j=i;j<n;j++)M[k][j]-=f*M[i][j]}}return d}
function inverse(A){if(A.length!==A[0].length)throw Error('反矩陣只適用方陣');const n=A.length,M=A.map((r,i)=>r.concat(r.map((_,j)=>i===j?1:0)));for(let i=0;i<n;i++){let p=i;for(let k=i+1;k<n;k++)if(Math.abs(M[k][i])>Math.abs(M[p][i]))p=k;if(Math.abs(M[p][i])<1e-12)throw Error('矩陣不可逆');[M[p],M[i]]=[M[i],M[p]];const v=M[i][i];for(let j=0;j<2*n;j++)M[i][j]/=v;for(let k=0;k<n;k++)if(k!==i){const f=M[k][i];for(let j=0;j<2*n;j++)M[k][j]-=f*M[i][j]}}return M.map(r=>r.slice(n))}
function matrixAction(fn){try{$('matrixResult').innerHTML=fn()}catch(e){$('matrixResult').innerHTML='<span class="error">'+e.message+'</span>'}}
$('matrixAdd').onclick=()=>matrixAction(()=>{const A=parseMatrix($('matrixA').value),B=parseMatrix($('matrixB').value),R=addMat(A,B);addHistory('矩陣加法','A + B',matrixText(R).replace(/<br>/g,' / '));return '<div class="result-title">A + B</div>'+matrixText(R)});$('matrixMul').onclick=()=>matrixAction(()=>{const R=mulMat(parseMatrix($('matrixA').value),parseMatrix($('matrixB').value));return '<div class="result-title">A × B</div>'+matrixText(R)});$('matrixDet').onclick=()=>matrixAction(()=>`<div class="result-title">det(A)</div>${fmt(det(parseMatrix($('matrixA').value)))}`);$('matrixInv').onclick=()=>matrixAction(()=>`<div class="result-title">A⁻¹</div>${matrixText(inverse(parseMatrix($('matrixA').value)))}`);

// Combinatorics / probability
$('calcComb').onclick=()=>{try{const n=+$('combN').value,r=+$('combR').value;if(!Number.isInteger(n)||!Number.isInteger(r)||n<0||r<0||r>n)throw Error('請滿足 n、r 為整數且 0 ≤ r ≤ n');const P=factorial(n)/factorial(n-r),C=P/factorial(r);$('combResult').innerHTML=`<div>n! = ${fmt(factorial(n))}</div><div>P(n,r) = ${fmt(P)}</div><div>C(n,r) = ${fmt(C)}</div>`;addHistory('排列組合',`n=${n}, r=${r}`,`P=${fmt(P)}, C=${fmt(C)}`)}catch(e){$('combResult').innerHTML='<span class="error">'+e.message+'</span>'}};
$('calcProb').onclick=()=>{try{const A=+$('probA').value,B=+$('probB').value,n=+$('binN').value,k=+$('binK').value,p=+$('binP').value;if([A,B,p].some(x=>x<0||x>1)||!Number.isInteger(n)||!Number.isInteger(k)||k<0||k>n)throw Error('機率須介於 0～1，n、k 必須是有效整數');const bin=factorial(n)/(factorial(k)*factorial(n-k))*p**k*(1-p)**(n-k);$('probResult').innerHTML=`<div>P(Aᶜ) = ${fmt(1-A)}</div><div>若 A、B 獨立：P(A∩B) = ${fmt(A*B)}</div><div>若 A、B 獨立：P(A∪B) = ${fmt(A+B-A*B)}</div><div>二項分布 P(X=${k}) = ${fmt(bin)}</div>`;addHistory('機率',`P(A)=${A}, P(B)=${B}, n=${n}, k=${k}, p=${p}`,`二項機率=${fmt(bin)}`)}catch(e){$('probResult').innerHTML='<span class="error">'+e.message+'</span>'}};

// Geometry
function geom(id,html,input){$(id).innerHTML=html;addHistory('幾何',input,html.replace(/<[^>]+>/g,' '))}
$('calcCircle').onclick=()=>{const r=+$('circleR').value;geom('circleResult',`面積 = ${fmt(Math.PI*r*r)}<br>周長 = ${fmt(2*Math.PI*r)}`,`圓 r=${r}`)};$('calcRect').onclick=()=>{const a=+$('rectW').value,b=+$('rectH').value;geom('rectResult',`面積 = ${fmt(a*b)}<br>周長 = ${fmt(2*(a+b))}`,`矩形 ${a}×${b}`)};$('calcTri').onclick=()=>{const b=+$('triB').value,h=+$('triH').value;geom('triResult',`面積 = ${fmt(b*h/2)}`,`三角形 b=${b}, h=${h}`)};$('calcTrap').onclick=()=>{const a=+$('trapA').value,b=+$('trapB').value,h=+$('trapH').value;geom('trapResult',`面積 = ${fmt((a+b)*h/2)}`,`梯形 ${a},${b},h=${h}`)};$('calcSphere').onclick=()=>{const r=+$('sphereR').value;geom('sphereResult',`表面積 = ${fmt(4*Math.PI*r*r)}<br>體積 = ${fmt(4*Math.PI*r**3/3)}`,`球 r=${r}`)};$('calcCylinder').onclick=()=>{const r=+$('cylR').value,h=+$('cylH').value;geom('cylResult',`表面積 = ${fmt(2*Math.PI*r*(r+h))}<br>體積 = ${fmt(Math.PI*r*r*h)}`,`圓柱 r=${r}, h=${h}`)};$('calcCone').onclick=()=>{const r=+$('coneR').value,h=+$('coneH').value,l=Math.sqrt(r*r+h*h);geom('coneResult',`斜高 = ${fmt(l)}<br>體積 = ${fmt(Math.PI*r*r*h/3)}`,`圓錐 r=${r}, h=${h}`)};$('calcDistance').onclick=()=>{const x1=+$('dx1').value,y1=+$('dy1').value,x2=+$('dx2').value,y2=+$('dy2').value;geom('distanceResult',`距離 = ${fmt(Math.hypot(x2-x1,y2-y1))}`,`距離 (${x1},${y1}) 到 (${x2},${y2})`)};

// Sequence
$('arithBtn').onclick=()=>setSeq('arith');$('geoBtn').onclick=()=>setSeq('geo');function setSeq(t){seqType=t;$('arithBtn').classList.toggle('active',t==='arith');$('geoBtn').classList.toggle('active',t==='geo');$('diffLabel').innerHTML=t==='arith'?'公差 d<input id="seqD" type="number" step="any" placeholder="可留空">':'公比 r<input id="seqD" type="number" step="any" placeholder="可留空">'}
$('solveSequence').onclick=()=>{try{const a=+$('seqA1').value,anRaw=$('seqAn').value.trim(),nRaw=$('seqN').value.trim(),dRaw=$('seqD').value.trim();let an=anRaw===''?null:+anRaw,n=nRaw===''?null:+nRaw,d=dRaw===''?null:+dRaw;if(!Number.isFinite(a))throw Error('首項無效');let html='';if(seqType==='arith'){if(d===null&&an!==null&&n!==null&&n!==1)d=(an-a)/(n-1);if(n===null&&an!==null&&d!==null&&d!==0)n=(an-a)/d+1;if(an===null&&n!==null&&d!==null)an=a+(n-1)*d;if(d===null)throw Error('請提供公差，或同時提供 aₙ 與 n');if(n!==null&&!Number.isInteger(n))throw Error('項數 n 必須是整數');if(n!==null)html+=`第 n 項 aₙ = ${fmt(an??(a+(n-1)*d))}<br>前 n 項和 Sₙ = ${fmt(n*(2*a+(n-1)*d)/2)}<br>公差 d = ${fmt(d)}`;else html+=`公差 d = ${fmt(d)}`}else{if(d===null&&an!==null&&n!==null&&n!==1)d=Math.pow(an/a,1/(n-1));if(n===null&&an!==null&&d!==null&&d!==0&&a!==0)n=Math.log(an/a)/Math.log(d)+1;if(an===null&&n!==null&&d!==null)an=a*Math.pow(d,n-1);if(d===null)throw Error('請提供公比，或同時提供 aₙ 與 n');if(n!==null&&!Number.isInteger(n))throw Error('項數 n 必須是整數');if(n!==null){const sum=d===1?a*n:a*(1-Math.pow(d,n))/(1-d);html+=`第 n 項 aₙ = ${fmt(an??a*Math.pow(d,n-1))}<br>前 n 項和 Sₙ = ${fmt(sum)}<br>公比 r = ${fmt(d)}`}else html+=`公比 r = ${fmt(d)}`}$('sequenceResult').innerHTML=html;addHistory('數列',`首項 ${a}`,html.replace(/<br>/g,' '))}catch(e){$('sequenceResult').innerHTML='<span class="error">'+e.message+'</span>'}};

// Units
const units={length:{label:'長度',units:{m:['公尺',1],km:['公里',1000],cm:['公分',.01],mm:['毫米',.001],in:['英吋',.0254],ft:['英尺',.3048],yd:['碼',.9144],mi:['英里',1609.344]}},area:{label:'面積',units:{m2:['平方公尺',1],km2:['平方公里',1e6],cm2:['平方公分',1e-4],ha:['公頃',1e4],acre:['英畝',4046.8564224]}},volume:{label:'體積',units:{m3:['立方公尺',1],L:['公升',.001],mL:['毫升',1e-6],cm3:['立方公分',1e-6],gal:['美制加侖',.003785411784]}},mass:{label:'質量',units:{kg:['公斤',1],g:['公克',.001],mg:['毫克',1e-6],lb:['磅',.45359237],oz:['盎司',.028349523125]}},time:{label:'時間',units:{s:['秒',1],min:['分鐘',60],h:['小時',3600],day:['天',86400]}},temperature:{label:'溫度',units:{C:['攝氏',1],F:['華氏',1],K:['開爾文',1]}}};
function fillUnits(){const cat=$('unitCategory').value,u=units[cat].units;const opts=Object.entries(u).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('');$('unitFrom').innerHTML=opts;$('unitTo').innerHTML=opts;$('unitTo').selectedIndex=Math.min(1,Object.keys(u).length-1)}fillUnits();$('unitCategory').onchange=fillUnits;
$('convertUnit').onclick=()=>{try{const cat=$('unitCategory').value,v=+$('unitValue').value,from=$('unitFrom').value,to=$('unitTo').value;let out;if(cat==='temperature'){const C=from==='C'?v:from==='F'?(v-32)*5/9:v-273.15;out=to==='C'?C:to==='F'?C*9/5+32:C+273.15}else{const base=v*units[cat].units[from][1];out=base/units[cat].units[to][1]}$('unitOutput').innerHTML=`<div class="unit-output">${fmt(v)} ${units[cat].units[from][0]} = ${fmt(out)} ${units[cat].units[to][0]}</div>`;addHistory('單位換算',`${v} ${units[cat].units[from][0]}`,`${fmt(out)} ${units[cat].units[to][0]}`)}catch(e){$('unitOutput').innerHTML='<span class="error">'+e.message+'</span>'}};

// Chemical equation balancing
function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a}function lcm(a,b){return Math.abs(a/gcd(a,b)*b)}
function parseFormula(formula){let i=0;function group(){const counts={};while(i<formula.length){if(formula[i]===')'){i++;break}if(formula[i]==='('){i++;const sub=group();let num=readNum();for(const e in sub)counts[e]=(counts[e]||0)+sub[e]*num;continue}if(!/[A-Z]/.test(formula[i]))throw Error('化學式格式錯誤：'+formula);let el=formula[i++];while(i<formula.length&&/[a-z]/.test(formula[i]))el+=formula[i++];const num=readNum();counts[el]=(counts[el]||0)+num}return counts}function readNum(){let s='';while(i<formula.length&&/[0-9]/.test(formula[i]))s+=formula[i++];return s?parseInt(s):1}const r=group();if(i!==formula.length)throw Error('化學式括號不完整：'+formula);return r}
function rref(A){const m=A.length,n=A[0].length;let row=0,piv=[];for(let col=0;col<n&&row<m;col++){let p=row;for(let r=row+1;r<m;r++)if(Math.abs(A[r][col])>Math.abs(A[p][col]))p=r;if(Math.abs(A[p][col])<1e-12)continue;[A[p],A[row]]=[A[row],A[p]];const v=A[row][col];for(let j=col;j<n;j++)A[row][j]/=v;for(let r=0;r<m;r++)if(r!==row){const f=A[r][col];if(Math.abs(f)>1e-12)for(let j=col;j<n;j++)A[r][j]-=f*A[row][j]}piv.push(col);row++}return piv}
function balanceEquation(eq){let clean=eq.replace(/\s+/g,'').replace(/→|=>|=/,'->');const sides=clean.split('->');if(sides.length!==2)throw Error('請使用 -> 分隔反應物與生成物');const left=sides[0].split('+').filter(Boolean),right=sides[1].split('+').filter(Boolean);if(!left.length||!right.length)throw Error('左右兩邊都需要化學物質');const formulas=[...left,...right], parsed=formulas.map(parseFormula), elements=[...new Set(parsed.flatMap(x=>Object.keys(x)))];const M=elements.map(el=>parsed.map((c,j)=>(j<left.length?1:-1)*(c[el]||0)));const R=M.map(r=>r.map(v=>v));const piv=rref(R);const pivotSet=new Set(piv),free=[...Array(formulas.length).keys()].filter(i=>!pivotSet.has(i));if(!free.length)throw Error('找不到可用的配平解');const v=Array(formulas.length).fill(0);v[free[0]]=1;for(let i=piv.length-1;i>=0;i--){const col=piv[i];let sum=0;for(let j=col+1;j<formulas.length;j++)sum+=R[i][j]*v[j];v[col]=-sum}let den=1;v.forEach(x=>{const s=String(Math.abs(x));if(!Number.isInteger(x)){const d=(s.split('.')[1]||'').length;den*=10**d}});let coeff=v.map(x=>Math.round(x*den));let g=coeff.reduce((a,b)=>gcd(a,b),0);coeff=coeff.map(x=>x/g);if(coeff.some(x=>x<0))coeff=coeff.map(x=>-x);if(coeff.every(x=>x===0))throw Error('無法取得有效係數');const lhs=left.map((f,i)=>`${coeff[i]===1?'':coeff[i]}${f}`).join(' + '),rhs=right.map((f,i)=>`${coeff[left.length+i]===1?'':coeff[left.length+i]}${f}`).join(' + ');return {lhs,rhs,coeff,elements}}
function prettyFormula(s){return escapeHtml(s).replace(/([A-Z][a-z]?)(\d+)/g,'$1<sub>$2</sub>')}
$('balanceChemical').onclick=()=>{try{const input=$('chemicalInput').value,r=balanceEquation(input);$('chemicalResult').innerHTML=`<div class="result-title success">配平完成</div><div class="formula">${prettyFormula(r.lhs)} → ${prettyFormula(r.rhs)}</div><div class="step">係數：${r.coeff.join('、')}</div><div class="step">檢查元素：${r.elements.join('、')}</div>`;addHistory('化學方程式',input,`${r.lhs} -> ${r.rhs}`)}catch(e){$('chemicalResult').innerHTML='<span class="error">'+escapeHtml(e.message)+'</span>'}};document.querySelectorAll('[data-chem]').forEach(b=>b.onclick=()=>{$('chemicalInput').value=b.dataset.chem});

drawGraph();
})();
