
(() => {
'use strict';
const $=id=>document.getElementById(id);
const fmt=n=>Number.isFinite(n)?(Math.abs(n)<1e-12?0:Number(n.toFixed(10))).toString():String(n);
const esc=s=>String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const HIST='mathbox-history-v5'; let angleDeg=true, seqType='arith';
const theme=localStorage.getItem('mathbox-theme'); if(theme==='dark') document.body.classList.add('dark');
if($('themeToggle')){$('themeToggle').textContent=document.body.classList.contains('dark')?'☀️':'🌙';$('themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('mathbox-theme',document.body.classList.contains('dark')?'dark':'light');$('themeToggle').textContent=document.body.classList.contains('dark')?'☀️':'🌙';if(typeof drawGraph==='function')drawGraph()}}
function addHistory(type,input,result){let h=JSON.parse(localStorage.getItem(HIST)||'[]');h.unshift({type,input,result,time:new Date().toLocaleString('zh-TW')});localStorage.setItem(HIST,JSON.stringify(h.slice(0,100)));if($('historyList'))renderHistory()}
function renderHistory(){const h=JSON.parse(localStorage.getItem(HIST)||'[]');$('historyList').innerHTML=h.length?h.map((x,i)=>`<div class="history-item"><div><div class="history-value">${esc(x.type)}：${esc(x.input)}</div><div>${esc(x.result)}</div><div class="history-meta">${esc(x.time)}</div></div><button class="secondary" data-del-history="${i}">刪除</button></div>`).join(''):'<div class="empty">目前沒有計算紀錄</div>';document.querySelectorAll('[data-del-history]').forEach(b=>b.onclick=()=>{let a=JSON.parse(localStorage.getItem(HIST)||'[]');a.splice(+b.dataset.delHistory,1);localStorage.setItem(HIST,JSON.stringify(a));renderHistory()})}
if($('historyList')){renderHistory();$('clearHistory').onclick=()=>{if(confirm('確定要清除全部紀錄嗎？')){localStorage.removeItem(HIST);renderHistory()}}}
function factorial(n){n=Number(n);if(!Number.isInteger(n)||n<0||n>170)throw Error('階乘只支援 0～170 的整數');let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function prepareExpr(expr){let s=String(expr).trim().replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('π','PI').replace(/\^/g,'**');if(!/^[0-9A-Za-z_+\-*/().,%\s]+$/.test(s))throw Error('含有不支援的符號');s=s.replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');s=s.replace(/(\d|\)|PI|E|x)\s*(?=(PI|E|x|sin|cos|tan|sqrt|abs|ln|log)\s*\()/g,'$1*');s=s.replace(/(\d|\)|PI|E|x)\s*(?=(PI|E|x))/g,'$1*');return s}
function evaluateExpression(expr,x=0){let s=prepareExpr(expr);if((s.match(/\(/g)||[]).length!==(s.match(/\)/g)||[]).length)throw Error('括號數量不一致');s=s.replace(/(\d+(?:\.\d+)?|\([^()]+\))!/g,'factorial($1)');const args=['sin','cos','tan','sqrt','abs','ln','log','exp','floor','ceil','round','factorial','PI','E','x'];const vals=[a=>angleDeg?Math.sin(a*Math.PI/180):Math.sin(a),a=>angleDeg?Math.cos(a*Math.PI/180):Math.cos(a),a=>angleDeg?Math.tan(a*Math.PI/180):Math.tan(a),Math.sqrt,Math.abs,Math.log,Math.log10,Math.exp,Math.floor,Math.ceil,Math.round,factorial,Math.PI,Math.E,x];const v=new Function(...args,'return ('+s+');')(...vals);if(!Number.isFinite(v))throw Error('結果不是有限數值');return v}
if($('angleMode'))$('angleMode').onclick=()=>{angleDeg=!angleDeg;$('angleMode').textContent=angleDeg?'度 DEG':'弧度 RAD';$('angleMode').classList.toggle('active',angleDeg)};
if($('calcDisplay')){const calc=()=>{const input=$('calcDisplay').value;if(!input.trim())return;try{const v=evaluateExpression(input);$('calcDisplay').value=fmt(v);addHistory('計算機',input,fmt(v))}catch(e){$('calcDisplay').value='錯誤：'+e.message}};document.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>{const v=b.dataset.calc,d=$('calcDisplay');if(v==='=')return calc();if(v==='C')d.value='';else if(v==='⌫')d.value=d.value.slice(0,-1);else d.value+=v;d.focus()});$('calcDisplay').onkeydown=e=>{if(e.key==='Enter')calc()}}
if($('solveQuadratic'))$('solveQuadratic').onclick=()=>{const a=+$('qa').value,b=+$('qb').value,c=+$('qc').value,r=$('quadraticResult');if(!Number.isFinite(a)||!Number.isFinite(b)||!Number.isFinite(c)||a===0){r.innerHTML='<span class="error">a 不可為 0，且係數必須是數字。</span>';return}const D=b*b-4*a*c;let h=`<div class="result-title">判別式 Δ = ${fmt(D)}</div><div class="step">Δ = b² − 4ac = ${fmt(D)}</div>`;if(D>0){const x1=(-b+Math.sqrt(D))/(2*a),x2=(-b-Math.sqrt(D))/(2*a);h+=`<div class="step">x = (−b ± √Δ)/(2a)</div><div class="success">x₁ = ${fmt(x1)}，x₂ = ${fmt(x2)}</div>`}else if(D===0){h+=`<div class="success">重根 x = ${fmt(-b/(2*a))}</div>`}else{h+=`<div>沒有實數根。</div><div class="success">複數根：${fmt(-b/(2*a))} ± ${fmt(Math.sqrt(-D)/(2*a))}i</div>`}r.innerHTML=h;addHistory('二次方程式',`a=${a}, b=${b}, c=${c}`,h.replace(/<[^>]+>/g,' '))};
let canvas,ctx,view={xmin:-10,xmax:10,ymin:-10,ymax:10};
function niceStep(v){const p=10**Math.floor(Math.log10(v||1)),q=v/p;return(q<=1?1:q<=2?2:q<=5?5:10)*p}
function syncView(){view.xmin=+$('xMin').value;view.xmax=+$('xMax').value;view.ymin=+$('yMin').value;view.ymax=+$('yMax').value}
function drawGraph(){if(!$('graphCanvas'))return;canvas=$('graphCanvas');ctx=canvas.getContext('2d');try{syncView();if(!(view.xmax>view.xmin&&view.ymax>view.ymin))throw Error('座標範圍無效');const w=canvas.width,h=canvas.height,dark=document.body.classList.contains('dark'),grid=dark?'#334056':'#dfe6ef',axis=dark?'#e8edf7':'#334155',text=dark?'#aeb9cc':'#64748b',X=x=>(x-view.xmin)/(view.xmax-view.xmin)*w,Y=y=>h-(y-view.ymin)/(view.ymax-view.ymin)*h;ctx.clearRect(0,0,w,h);ctx.strokeStyle=grid;ctx.lineWidth=1;const sx=niceStep((view.xmax-view.xmin)/10),sy=niceStep((view.ymax-view.ymin)/10);for(let x=Math.ceil(view.xmin/sx)*sx;x<=view.xmax;x+=sx){ctx.beginPath();ctx.moveTo(X(x),0);ctx.lineTo(X(x),h);ctx.stroke()}for(let y=Math.ceil(view.ymin/sy)*sy;y<=view.ymax;y+=sy){ctx.beginPath();ctx.moveTo(0,Y(y));ctx.lineTo(w,Y(y));ctx.stroke()}ctx.strokeStyle=axis;ctx.lineWidth=1.5;if(view.xmin<=0&&view.xmax>=0){ctx.beginPath();ctx.moveTo(X(0),0);ctx.lineTo(X(0),h);ctx.stroke()}if(view.ymin<=0&&view.ymax>=0){ctx.beginPath();ctx.moveTo(0,Y(0));ctx.lineTo(w,Y(0));ctx.stroke()}ctx.fillStyle=text;ctx.font='12px sans-serif';const expr=$('functionInput').value;ctx.strokeStyle='#4169e1';ctx.lineWidth=2.5;ctx.beginPath();let started=false,prev=null;for(let px=0;px<w;px++){const x=view.xmin+(view.xmax-view.xmin)*px/(w-1);let y;try{y=evaluateExpression(expr,x)}catch{continue}if(Math.abs(y)>1e7){started=false;prev=null;continue}const py=Y(y);if(!started||prev===null||Math.abs(py-prev)>h*1.5){ctx.moveTo(px,py);started=true}else ctx.lineTo(px,py);prev=py}ctx.stroke();$('graphMessage').textContent=''}catch(e){$('graphMessage').textContent=e.message}}
if($('graphCanvas')){canvas=$('graphCanvas');ctx=canvas.getContext('2d');$('drawGraph').onclick=drawGraph;$('resetGraph').onclick=()=>{$('functionInput').value='x^2-4';$('xMin').value=-10;$('xMax').value=10;$('yMin').value=-10;$('yMax').value=10;drawGraph()};document.querySelectorAll('[data-insert]').forEach(b=>b.onclick=()=>{$('functionInput').value+=b.dataset.insert;drawGraph()});let drag=false,last={x:0,y:0};canvas.onpointerdown=e=>{drag=true;last={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-last.x,dy=e.clientY-last.y,sx=(view.xmax-view.xmin)/canvas.clientWidth,sy=(view.ymax-view.ymin)/canvas.clientHeight;view.xmin-=dx*sx;view.xmax-=dx*sx;view.ymin+=dy*sy;view.ymax+=dy*sy;$('xMin').value=view.xmin;$('xMax').value=view.xmax;$('yMin').value=view.ymin;$('yMax').value=view.ymax;last={x:e.clientX,y:e.clientY};drawGraph()};canvas.onpointerup=()=>drag=false;canvas.ondblclick=()=>$('resetGraph').click();canvas.onwheel=e=>{e.preventDefault();syncView();const f=e.deltaY<0?.82:1.22,r=canvas.getBoundingClientRect(),mx=(e.clientX-r.left)/r.width,my=(e.clientY-r.top)/r.height,cx=view.xmin+mx*(view.xmax-view.xmin),cy=view.ymax-my*(view.ymax-view.ymin);view.xmin=cx+(view.xmin-cx)*f;view.xmax=cx+(view.xmax-cx)*f;view.ymin=cy+(view.ymin-cy)*f;view.ymax=cy+(view.ymax-cy)*f;$('xMin').value=view.xmin;$('xMax').value=view.xmax;$('yMin').value=view.ymin;$('yMax').value=view.ymax;drawGraph()};drawGraph()}
if($('analyzeFunction'))$('analyzeFunction').onclick=()=>{const expr=$('analysisInput').value,a=+$('analysisMin').value,b=+$('analysisMax').value,r=$('analysisResult');if(!(b>a)){r.innerHTML='<span class="error">分析範圍無效。</span>';return}try{let min={x:a,y:Infinity},max={x:a,y:-Infinity},roots=[];const N=2000,dx=(b-a)/N;let prevX=a,prevY=evaluateExpression(expr,a);for(let i=0;i<=N;i++){const x=a+i*dx;let y;try{y=evaluateExpression(expr,x)}catch{continue}if(Number.isFinite(y)){if(y<min.y)min={x,y};if(y>max.y)max={x,y};if(i>0&&prevY*y<0){let lo=prevX,hi=x;for(let k=0;k<35;k++){const mid=(lo+hi)/2,ym=evaluateExpression(expr,mid);if(prevY*ym<=0)hi=mid;else{lo=mid;prevY=ym}}roots.push((lo+hi)/2)}prevX=x;prevY=y}}let h=`<div>近似最小值：(${fmt(min.x)}, ${fmt(min.y)})</div><div>近似最大值：(${fmt(max.x)}, ${fmt(max.y)})</div><div>x 截距：${roots.length?roots.map(fmt).join('、'):'未找到'}</div><div>y 截距：${fmt(evaluateExpression(expr,0))}</div>`;const m=expr.match(/^\s*([+-]?\d*\.?\d+)\*?x\^2\s*([+-]\s*\d*\.?\d+)?\*?x?\s*([+-]\s*\d*\.?\d+)?\s*$/);if(m){const A=parseFloat(m[1]),B=m[2]?parseFloat(m[2].replace(/\s/g,'')):0,C=m[3]?parseFloat(m[3].replace(/\s/g,'')):0;const xv=-B/(2*A),yv=A*xv*xv+B*xv+C;h+=`<div>二次函數頂點：(${fmt(xv)}, ${fmt(yv)})</div><div>對稱軸：x = ${fmt(xv)}</div>`}r.innerHTML=h;addHistory('函數分析',expr,h.replace(/<[^>]+>/g,' '))}catch(e){r.innerHTML='<span class="error">'+esc(e.message)+'</span>'}};
if($('calcStats'))$('calcStats').onclick=()=>{const a=$('statsInput').value.split(/[\s,，]+/).map(Number).filter(Number.isFinite);const r=$('statsResult');if(!a.length){r.innerHTML='<span class="error">請輸入數字。</span>';return}a.sort((x,y)=>x-y);const n=a.length,mean=a.reduce((s,x)=>s+x,0)/n,median=n%2?a[(n-1)/2]:(a[n/2-1]+a[n/2])/2,modeMap={};a.forEach(x=>modeMap[x]=(modeMap[x]||0)+1);const maxF=Math.max(...Object.values(modeMap)),modes=maxF>1?Object.keys(modeMap).filter(x=>modeMap[x]===maxF):[];const popVar=a.reduce((s,x)=>s+(x-mean)**2,0)/n,sample=n>1?popVar*n/(n-1):NaN;r.innerHTML=`<div>筆數：${n}</div><div>平均數：${fmt(mean)}</div><div>中位數：${fmt(median)}</div><div>眾數：${modes.length?modes.join('、'):'無重複眾數'}</div><div>最小：${fmt(a[0])}　最大：${fmt(a[n-1])}</div><div>母體變異數：${fmt(popVar)}</div><div>樣本變異數：${fmt(sample)}</div><div>母體標準差：${fmt(Math.sqrt(popVar))}</div>`;addHistory('統計',$('statsInput').value,r.textContent)};
function parseMatrix(s){const rows=s.trim().split(/;|\n/).filter(Boolean).map(r=>r.trim().split(/[\s,，]+/).map(Number));if(!rows.length||rows.some(r=>r.length!==rows[0].length||r.some(x=>!Number.isFinite(x))))throw Error('矩陣格式錯誤');return rows}
function matText(A){return A.map(r=>r.map(fmt).join('　')).join('<br>')}
if($('matrixAdd')){const get=()=>[parseMatrix($('matrixA').value),parseMatrix($('matrixB').value)],out=h=>{$('matrixResult').innerHTML=h};$('matrixAdd').onclick=()=>{try{const[A,B]=get();if(A.length!==B.length||A[0].length!==B[0].length)throw Error('矩陣尺寸必須相同');out(matText(A.map((r,i)=>r.map((x,j)=>x+B[i][j]))))}catch(e){out('<span class="error">'+esc(e.message)+'</span>')}};$('matrixMul').onclick=()=>{try{const[A,B]=get();if(A[0].length!==B.length)throw Error('A 的欄數必須等於 B 的列數');const C=A.map(r=>B[0].map((_,j)=>r.reduce((s,x,k)=>s+x*B[k][j],0)));out(matText(C))}catch(e){out('<span class="error">'+esc(e.message)+'</span>')}};$('matrixDet').onclick=()=>{try{const A=parseMatrix($('matrixA').value);out('det(A) = '+fmt(det(A)))}catch(e){out('<span class="error">'+esc(e.message)+'</span>')}};$('matrixInv').onclick=()=>{try{out(matText(inv(parseMatrix($('matrixA').value))))}catch(e){out('<span class="error">'+esc(e.message)+'</span>')}}}
function det(A){if(A.length!==A[0].length)throw Error('行列式只支援方陣');let M=A.map(r=>r.slice()),d=1;for(let i=0;i<M.length;i++){let p=i;for(let j=i+1;j<M.length;j++)if(Math.abs(M[j][i])>Math.abs(M[p][i]))p=j;if(Math.abs(M[p][i])<1e-12)return 0;if(p!==i){[M[p],M[i]]=[M[i],M[p]];d=-d}const q=M[i][i];d*=q;for(let j=i+1;j<M.length;j++){const f=M[j][i]/q;for(let k=i+1;k<M.length;k++)M[j][k]-=f*M[i][k]}}return d}
function inv(A){if(A.length!==A[0].length)throw Error('反矩陣只支援方陣');const n=A.length,M=A.map((r,i)=>r.map(x=>x).concat(Array.from({length:n},(_,j)=>i===j?1:0)));for(let c=0;c<n;c++){let p=c;for(let r=c+1;r<n;r++)if(Math.abs(M[r][c])>Math.abs(M[p][c]))p=r;if(Math.abs(M[p][c])<1e-12)throw Error('矩陣不可逆');[M[p],M[c]]=[M[c],M[p]];const q=M[c][c];M[c]=M[c].map(x=>x/q);for(let r=0;r<n;r++)if(r!==c){const f=M[r][c];M[r]=M[r].map((x,j)=>x-f*M[c][j])}}return M.map(r=>r.slice(n))}
if($('calcComb'))$('calcComb').onclick=()=>{const n=+$('combN').value,r=+$('combR').value,o=$('combResult');try{if(!Number.isInteger(n)||!Number.isInteger(r)||n<0||r<0||r>n)throw Error('請輸入 0≤r≤n 的整數');const p=factorial(n)/factorial(n-r),c=p/factorial(r);o.innerHTML=`n! = ${fmt(factorial(n))}<br>P(n,r) = ${fmt(p)}<br>C(n,r) = ${fmt(c)}`;addHistory('排列組合',`n=${n}, r=${r}`,o.textContent)}catch(e){o.innerHTML='<span class="error">'+esc(e.message)+'</span>'}};
if($('calcProb'))$('calcProb').onclick=()=>{const A=+$('probA').value,B=+$('probB').value,n=+$('binN').value,k=+$('binK').value,p=+$('binP').value,o=$('probResult');try{if([A,B,p].some(x=>x<0||x>1)||n<0||k<0||!Number.isInteger(n)||!Number.isInteger(k)||k>n)throw Error('機率需在 0～1，n、k 必須為整數且 k≤n');const choose=factorial(n)/(factorial(k)*factorial(n-k));const bin=choose*p**k*(1-p)**(n-k);o.innerHTML=`P(A補集) = ${fmt(1-A)}<br>若 A、B 獨立：P(A∩B) = ${fmt(A*B)}<br>二項分布 P(X=k) = ${fmt(bin)}`;addHistory('機率',`P(A)=${A}, P(B)=${B}, n=${n}, k=${k}, p=${p}`,o.textContent)}catch(e){o.innerHTML='<span class="error">'+esc(e.message)+'</span>'}};
function bind(id,fn){if($(id))$(id).onclick=fn}
const geom=[['calcCircle',()=>{const r=+$('circleR').value;$('circleResult').textContent=`面積 = ${fmt(Math.PI*r*r)}；周長 = ${fmt(2*Math.PI*r)}`;},'circle'],['calcRect',()=>{$('rectResult').textContent=`面積 = ${fmt(+$('rectW').value*+$('rectH').value)}；周長 = ${fmt(2*(+$('rectW').value+ +$('rectH').value))}`},'rect'],['calcTri',()=>{$('triResult').textContent=`面積 = ${fmt(+$('triB').value*+$('triH').value/2)}`},'tri'],['calcTrap',()=>{$('trapResult').textContent=`面積 = ${fmt((+$('trapA').value+ +$('trapB').value)*+$('trapH').value/2)}`},'trap'],['calcSphere',()=>{const r=+$('sphereR').value;$('sphereResult').textContent=`表面積 = ${fmt(4*Math.PI*r*r)}；體積 = ${fmt(4*Math.PI*r*r*r/3)}`},'sphere'],['calcCylinder',()=>{const r=+$('cylR').value,h=+$('cylH').value;$('cylResult').textContent=`底面積 = ${fmt(Math.PI*r*r)}；體積 = ${fmt(Math.PI*r*r*h)}`},'cyl'],['calcCone',()=>{const r=+$('coneR').value,h=+$('coneH').value;$('coneResult').textContent=`底面積 = ${fmt(Math.PI*r*r)}；體積 = ${fmt(Math.PI*r*r*h/3)}`},'cone'],['calcDistance',()=>{const dx=+$('dx2').value-+$('dx1').value,dy=+$('dy2').value-+$('dy1').value;$('distanceResult').textContent=`距離 = ${fmt(Math.hypot(dx,dy))}`},'distance']];geom.forEach(([id,fn])=>bind(id,fn));
if($('arithBtn')){$('arithBtn').onclick=()=>{seqType='arith';$('arithBtn').classList.add('active');$('geoBtn').classList.remove('active');$('diffLabel').firstChild.textContent='公差 d';};$('geoBtn').onclick=()=>{seqType='geo';$('geoBtn').classList.add('active');$('arithBtn').classList.remove('active');$('diffLabel').firstChild.textContent='公比 r';};$('solveSequence').onclick=()=>{const a=+$('seqA1').value,an=$('seqAn').value===''?null:+$('seqAn').value,n=$('seqN').value===''?null:+$('seqN').value,d=$('seqD').value===''?null:+$('seqD').value,o=$('sequenceResult');try{let common=d;if(an!==null&&n!==null&&n!==1){common=seqType==='arith'?(an-a)/(n-1):Math.pow(an/a,1/(n-1))}if(common===null)throw Error('至少提供公差/公比，或同時提供 aₙ 與 n');let N=n;if(N===null&&an!==null&&seqType==='arith')N=Math.round((an-a)/common+1);if(N===null)throw Error('請提供 n 或可反推的 aₙ');let nth=N?seqType==='arith'?a+(N-1)*common:a*common**(N-1):a;let sum=seqType==='arith'?N*(a+nth)/2:(Math.abs(common-1)<1e-12?a*N:a*(common**N-1)/(common-1));o.innerHTML=`${seqType==='arith'?'公差':'公比'} = ${fmt(common)}<br>第 ${N} 項 = ${fmt(nth)}<br>前 ${N} 項和 = ${fmt(sum)}`;addHistory('數列',o.textContent,o.textContent)}catch(e){o.innerHTML='<span class="error">'+esc(e.message)+'</span>'}}}
const units={length:{m:1,cm:.01,mm:.001,km:1000,ft:.3048,in:.0254},area:{'m²':1,'cm²':1e-4,'km²':1e6,'ft²':.09290304},volume:{L:.001,mL:1e-6,'m³':1,'cm³':1e-6,'ft³':.0283168466},mass:{kg:1,g:.001,mg:1e-6,lb:.45359237},time:{s:1,min:60,h:3600,day:86400}};
function fillUnits(){const cat=$('unitCategory').value,opts=Object.keys(units[cat]||{});$('unitFrom').innerHTML=opts.map(x=>`<option>${x}</option>`).join('');$('unitTo').innerHTML=opts.map(x=>`<option>${x}</option>`).join('');if(cat==='length')$('unitTo').value='cm'}
if($('unitCategory')){$('unitCategory').onchange=fillUnits;fillUnits();$('convertUnit').onclick=()=>{const cat=$('unitCategory').value,v=+$('unitValue').value,f=$('unitFrom').value,t=$('unitTo').value,o=$('unitOutput');if(cat==='temperature'){let c=f==='C'?v:f==='F'?(v-32)*5/9:v-273.15;let z=t==='C'?c:t==='F'?c*9/5+32:c+273.15;o.textContent=`${fmt(z)} ${t}`}else{o.textContent=`${fmt(v*units[cat][f]/units[cat][t])} ${t}`}addHistory('單位換算',`${v} ${f} → ${t}`,o.textContent)}}

// Chemistry: exact rational linear algebra + interactive periodic table
const elements=[
['H','氫',1,1,1],['He','氦',2,18,1],['Li','鋰',3,1,2],['Be','鈹',4,2,2],['B','硼',5,13,2],['C','碳',6,14,2],['N','氮',7,15,2],['O','氧',8,16,2],['F','氟',9,17,2],['Ne','氖',10,18,2],['Na','鈉',11,1,3],['Mg','鎂',12,2,3],['Al','鋁',13,13,3],['Si','矽',14,14,3],['P','磷',15,15,3],['S','硫',16,16,3],['Cl','氯',17,17,3],['Ar','氬',18,18,3],['K','鉀',19,1,4],['Ca','鈣',20,2,4],['Sc','鈧',21,3,4],['Ti','鈦',22,4,4],['V','釩',23,5,4],['Cr','鉻',24,6,4],['Mn','錳',25,7,4],['Fe','鐵',26,8,4],['Co','鈷',27,9,4],['Ni','鎳',28,10,4],['Cu','銅',29,11,4],['Zn','鋅',30,12,4],['Ga','鎵',31,13,4],['Ge','鍺',32,14,4],['As','砷',33,15,4],['Se','硒',34,16,4],['Br','溴',35,17,4],['Kr','氪',36,18,4],['Rb','銣',37,1,5],['Sr','鍶',38,2,5],['Y','釔',39,3,5],['Zr','鋯',40,4,5],['Nb','鈮',41,5,5],['Mo','鉬',42,6,5],['Tc','鎝',43,7,5],['Ru','釕',44,8,5],['Rh','銠',45,9,5],['Pd','鈀',46,10,5],['Ag','銀',47,11,5],['Cd','鎘',48,12,5],['In','銦',49,13,5],['Sn','錫',50,14,5],['Sb','銻',51,15,5],['Te','碲',52,16,5],['I','碘',53,17,5],['Xe','氙',54,18,5],['Cs','銫',55,1,6],['Ba','鋇',56,2,6],['La','鑭',57,3,6],['Ce','鈰',58,4,8],['Pr','鐠',59,5,8],['Nd','釹',60,6,8],['Pm','鉕',61,7,8],['Sm','釤',62,8,8],['Eu','銪',63,9,8],['Gd','釓',64,10,8],['Tb','鋱',65,11,8],['Dy','鏑',66,12,8],['Ho','鈥',67,13,8],['Er','鉺',68,14,8],['Tm','銩',69,15,8],['Yb','鐿',70,16,8],['Lu','鎦',71,17,8],['Hf','鉿',72,4,6],['Ta','鉭',73,5,6],['W','鎢',74,6,6],['Re','錸',75,7,6],['Os','鋨',76,8,6],['Ir','銥',77,9,6],['Pt','鉑',78,10,6],['Au','金',79,11,6],['Hg','汞',80,12,6],['Tl','鉈',81,13,6],['Pb','鉛',82,14,6],['Bi','鉍',83,15,6],['Po','釙',84,16,6],['At','砈',85,17,6],['Rn','氡',86,18,6],['Fr','鍅',87,1,7],['Ra','鐳',88,2,7],['Ac','錒',89,3,9],['Th','釷',90,4,9],['Pa','鏷',91,5,9],['U','鈾',92,6,9],['Np','錼',93,7,9],['Pu','鈽',94,8,9],['Am','鋂',95,9,9],['Cm','鋦',96,10,9],['Bk','鉳',97,11,9],['Cf','鉲',98,12,9],['Es','鑀',99,13,9],['Fm','鐨',100,14,9],['Md','鍆',101,15,9],['No','鍩',102,16,9],['Lr','鐒',103,17,9],['Rf','鑪',104,4,7],['Db','𨧀',105,5,7],['Sg','𨭎',106,6,7],['Bh','𨨏',107,7,7],['Hs','𨭆',108,8,7],['Mt','䥑',109,9,7],['Ds','鐽',110,10,7],['Rg','錀',111,11,7],['Cn','鎶',112,12,7],['Nh','鉨',113,13,7],['Fl','鈇',114,14,7],['Mc','鏌',115,15,7],['Lv','鉝',116,16,7],['Ts','鿬',117,17,7],['Og','鿫',118,18,7]
];
function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b){[a,b]=[b,a%b]}return a||1}function lcm(a,b){return Math.abs(a/gcd(a,b)*b)}
function parseFormula(f){let i=0;function num(){let s='';while(i<f.length&&/[0-9]/.test(f[i]))s+=f[i++];return s?parseInt(s):1}function group(){const c={};while(i<f.length){if(f[i]===')'){i++;break}if(f[i]==='('){i++;const s=group(),n=num();for(const e in s)c[e]=(c[e]||0)+s[e]*n;continue}if(!/[A-Z]/.test(f[i]))throw Error('化學式格式錯誤：'+f);let e=f[i++];while(i<f.length&&/[a-z]/.test(f[i]))e+=f[i++];c[e]=(c[e]||0)+num()}return c}const r=group();if(i!==f.length)throw Error('括號不完整：'+f);return r}
function f(n,d=1){if(d<0){n=-n;d=-d}if(n===0)return [0,1];const g=gcd(Math.abs(n),Math.abs(d));return [n/g,d/g]}
function fAdd(a,b){return f(a[0]*b[1]+b[0]*a[1],a[1]*b[1])}
function fSub(a,b){return f(a[0]*b[1]-b[0]*a[1],a[1]*b[1])}
function fMul(a,b){return f(a[0]*b[0],a[1]*b[1])}
function fDiv(a,b){if(b[0]===0)throw Error('分數除以零');return f(a[0]*b[1],a[1]*b[0])}
function rrefFraction(A){let m=A.length,n=A[0].length,row=0,piv=[];for(let col=0;col<n&&row<m;col++){let p=row;while(p<m&&A[p][col][0]===0)p++;if(p===m)continue;[A[p],A[row]]=[A[row],A[p]];const pv=A[row][col];A[row]=A[row].map(x=>fDiv(x,pv));for(let r=0;r<m;r++){if(r===row)continue;const factor=A[r][col];if(factor[0]===0)continue;A[r]=A[r].map((x,j)=>fSub(x,fMul(factor,A[row][j])))}piv.push(col);row++}return piv}
function balanceEquation(eq){const clean=eq.replace(/\s+/g,'').replace(/→|=>|=/,'->'),sides=clean.split('->');if(sides.length!==2)throw Error('請用 -> 分隔左右兩邊');const L=sides[0].split('+').filter(Boolean),Rside=sides[1].split('+').filter(Boolean);if(!L.length||!Rside.length)throw Error('左右兩邊都要有物質');const fs=[...L,...Rside],ps=fs.map(parseFormula),els=[...new Set(ps.flatMap(x=>Object.keys(x)))];const M=els.map(e=>fs.map((_,j)=>f((j<L.length?1:-1)*(ps[j][e]||0))));const reduced=M.map(r=>r.map(x=>x.slice()));const piv=rrefFraction(reduced);const free=[...Array(fs.length).keys()].filter(i=>!piv.includes(i));if(!free.length)throw Error('這個反應式沒有非零自由解');const v=Array(fs.length).fill(null).map(()=>f(0));v[free[0]]=f(1);for(let i=piv.length-1;i>=0;i--){const col=piv[i];let sum=f(0);for(let j=col+1;j<fs.length;j++)sum=fAdd(sum,fMul(reduced[i][j],v[j]));v[col]=f(-sum[0],sum[1])}let den=1;v.forEach(x=>den=lcm(den,x[1]));let co=v.map(x=>x[0]*(den/x[1]));let g=co.reduce((a,b)=>gcd(a,b),0);co=co.map(x=>x/g);if(co.some(x=>x<0))co=co.map(x=>-x);if(co.some(x=>x<=0))throw Error('無法取得正整數係數，請確認化學式與反應式是否合理');return {L,R:Rside,co,els}}
function prettyFormula(s){return s.replace(/([A-Za-z)])(\d+)/g,'$1<sub>$2</sub>')}
function showBalanced(r,target){const g=r.co.reduce((a,b)=>gcd(a,b),0);if(g!==1)throw Error('係數沒有化成最簡整數比');const lhs=r.L.map((f,i)=>`${r.co[i]===1?'':r.co[i]}${f}`).join(' + '),rhs=r.R.map((f,i)=>`${r.co[r.L.length+i]===1?'':r.co[r.L.length+i]}${f}`).join(' + ');target.innerHTML=`<div class="result-title success">配平完成</div><div class="formula">${prettyFormula(lhs)} → ${prettyFormula(rhs)}</div><div class="step">最簡整數比：${r.co.join(' : ')}</div><div class="step">最大公因數：${g}</div><div class="step">檢查元素：${r.els.join('、')}</div><div class="hint">提示：係數 1 會省略不顯示，但仍會列在上面的整數比中。</div>`;addHistory('化學方程式',r.L.join(' + ')+' -> '+r.R.join(' + '),lhs+' -> '+rhs)}
if($('balanceChemical')){$('balanceChemical').onclick=()=>{try{showBalanced(balanceEquation($('chemicalInput').value),$('chemicalResult'))}catch(e){$('chemicalResult').innerHTML='<span class="error">'+esc(e.message)+'</span>'}};document.querySelectorAll('[data-chem]').forEach(b=>b.onclick=()=>{$('chemicalInput').value=b.dataset.chem})}
let currentFormula=[],selectedSide='left';
function renderMolecule(){if(!$('moleculePreview'))return;const text=currentFormula.map(x=>x.symbol+(x.count===1?'':`<sub>${x.count}</sub>`)).join('');$('moleculePreview').innerHTML='目前分子：'+(text||'—')}
function buildFormula(){return currentFormula.map(x=>x.symbol+(x.count===1?'':x.count)).join('')}
function renderMolecules(){for(const side of ['left','right']){$(side+'Molecules').innerHTML=(window[side+'Molecules']||[]).map((f,i)=>`<span class="molecule-chip">${prettyFormula(f)} <button data-remove="${side}:${i}" class="mini-x">×</button></span>`).join('')||'<span class="muted">尚無分子</span>'}document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const [s,i]=b.dataset.remove.split(':');window[s+'Molecules'].splice(+i,1);renderMolecules()})}
let leftMolecules=[],rightMolecules=[];window.leftMolecules=leftMolecules;window.rightMolecules=rightMolecules;
function initPeriodic(){const p=$('periodicTable');if(!p)return;const map=new Map(elements.map(e=>[e[0],e]));for(let z=1;z<=118;z++){const e=elements[z-1];const div=document.createElement('button');div.className='element';div.type='button';div.dataset.symbol=e[0];div.style.gridColumn=e[3];div.style.gridRow=e[4];div.innerHTML=`<span class="z">${e[2]}</span><span class="sym">${e[0]}</span><span class="ename">${e[1]}</span>`;div.onclick=()=>{$('selectedElement').textContent=`已選：${e[0]} ${e[1]}（${e[2]}）`; $('elementCount').focus(); $('elementCount').select();$('addElement').dataset.symbol=e[0]};p.appendChild(div)} }
if($('periodicTable')){initPeriodic();document.querySelectorAll('input[name="chemSide"]').forEach(x=>x.onchange=()=>selectedSide=x.value);$('addElement').onclick=()=>{const s=$('addElement').dataset.symbol;if(!s){$('selectedElement').textContent='請先點選週期表中的元素';return}const n=Math.max(1,Math.min(99,parseInt($('elementCount').value)||1));currentFormula.push({symbol:s,count:n});renderMolecule()};$('clearMolecule').onclick=()=>{currentFormula=[];renderMolecule()};$('addMolecule').onclick=()=>{try{const f=buildFormula();if(!f)throw Error('目前分子是空的');(selectedSide==='left'?leftMolecules:rightMolecules).push(f);currentFormula=[];renderMolecule();renderMolecules();$('builtResult').innerHTML='<div class="success">已加入 '+prettyFormula(f)+'，可以繼續建立下一個分子。</div>'}catch(e){$('builtResult').innerHTML='<span class="error">'+esc(e.message)+'</span>'}};$('balanceBuilt').onclick=()=>{try{if(!leftMolecules.length||!rightMolecules.length)throw Error('請先把反應物與生成物都加入反應式');showBalanced(balanceEquation(leftMolecules.join('+')+'->'+rightMolecules.join('+')),$('builtResult'))}catch(e){$('builtResult').innerHTML='<span class="error">'+esc(e.message)+'</span>'}};renderMolecule();renderMolecules()}
})();
